export const PAISES = [
  { codigo: "AR", nombre: "Argentina" },
  { codigo: "BR", nombre: "Brasil" },
  { codigo: "CO", nombre: "Colombia" },
  { codigo: "CL", nombre: "Chile" },
  { codigo: "UY", nombre: "Uruguay" },
  { codigo: "PE", nombre: "Perú" },
  { codigo: "EC", nombre: "Ecuador" },
  { codigo: "VE", nombre: "Venezuela" },
  { codigo: "BO", nombre: "Bolivia" },
  { codigo: "PY", nombre: "Paraguay" },
  { codigo: "PA", nombre: "Panamá" },
  { codigo: "CR", nombre: "Costa Rica" },
  { codigo: "NI", nombre: "Nicaragua" },
  { codigo: "SV", nombre: "El Salvador" },
  { codigo: "GT", nombre: "Guatemala" },
  { codigo: "HN", nombre: "Honduras" },
  { codigo: "MX", nombre: "México" },
  { codigo: "US", nombre: "Estados Unidos" },
  { codigo: "ES", nombre: "España" },
  { codigo: "FR", nombre: "Francia" },
  { codigo: "IT", nombre: "Italia" },
  { codigo: "PT", nombre: "Portugal" },
  { codigo: "DE", nombre: "Alemania" },
  { codigo: "GB", nombre: "Inglaterra" },
  { codigo: "RU", nombre: "Rusia" },
  { codigo: "JP", nombre: "Japón" },
  { codigo: "CN", nombre: "China" },
  { codigo: "AU", nombre: "Australia" },
  { codigo: "CA", nombre: "Canadá" },
  { codigo: "IN", nombre: "India" },
  { codigo: "ZA", nombre: "Sudáfrica" },
  { codigo: "EG", nombre: "Egipto" },
  { codigo: "MA", nombre: "Marruecos" },
  { codigo: "NG", nombre: "Nigeria" },
];
